export const PROVIDER_ENGINE_NAME = '@FLEYE/STORAGE_ENGINE';
export const STORAGE_CONFIG = '@FLEYE/STORAGE_CONFIG'
export const STORAGE_CONFIG_MODULE_OPTIONS = '@FLEYE/STORAGE_CONFIG_MODULE_OPTIONS';
