name: Publish Package to npmjs
on:
  push:
    tags:
      - ^v[0-9]+\.[0-9]+\.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@fleye-me'

      - run: npm ci

      - name: Build project
        run: npm run build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}